---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resource-replicator.serviceAccountName" . }}
  labels:
    {{- include "resource-replicator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resource-replicator.fullname" . }}
  labels:
    {{- include "resource-replicator.labels" . | nindent 4 }}
rules:
- apiGroups: ["shopstic.com"]
  resources: ["replicatedresources"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resource-replicator.fullname" . }}
  labels:
    {{- include "resource-replicator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "resource-replicator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource-replicator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
