name: CI Workflow

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build-env:
    name: Build CI environment image
    runs-on: ubuntu-20.04
    outputs:
      image: ${{ steps.buildkit.outputs.image }}:${{ steps.buildkit.outputs.tag }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - run: chmod +r ~/.docker/config.json

      - name: Build and push shell Docker image
        id: buildkit
        uses: shopstic/buildkit-action@1.0.12
        with:
          context: ${{ github.workspace }}/images/shell
          image: ghcr.io/shopstic/k8s-resource-replicator-ci
          tag: ${{ hashFiles('images/shell/*') }}
          skipIfExists: true

  build-app:
    name: Build app image
    needs: build-env
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache deno
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.cache
          key: deno-${{ github.sha }}
          restore-keys: |
            deno-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: chmod +r ~/.docker/config.json

      - name: Compile
        env:
          SHELL_IMAGE: ${{ needs.build-env.outputs.image }}
          DENO_DIR: ${{ github.workspace }}/.cache/deno
        run: |-
          if ls "${DENO_DIR}" > /dev/null 2>&1; then
            du -sh "${DENO_DIR}"
          fi

          cat <<EOF | docker run \
            --workdir /repo \
            -i \
            --rm \
            -v "${GITHUB_WORKSPACE}:/repo" \
            -v "${DENO_DIR}:/root/.cache/deno" \
            -e "DENO_DIR=/root/.cache/deno" \
            "${SHELL_IMAGE}" \
            bash -l
          set -euo pipefail

          ./cli.sh code_quality
          ./cli.sh compile
          
          EOF

      - name: Github ref name
        id: ref_name
        run: |
          echo "GITHUB_REF=${GITHUB_REF}"

          BRANCH=""
          TAG=""
          if [[ "${GITHUB_REF}" =~ ^refs/heads/.* ]]; then
            BRANCH=${GITHUB_REF#refs/heads/}
          fi

          if [[ "${GITHUB_REF}" =~ ^refs/tags/.* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          elif [[ "${BRANCH}" == "main" ]]; then
            TAG=${GITHUB_SHA}
          fi

          echo "BRANCH=${BRANCH}"
          echo "TAG=${TAG}"
          echo "::set-output name=branch::${BRANCH}"
          echo "::set-output name=tag::${TAG}"

      - name: Build and push app Docker image
        uses: shopstic/buildkit-action@1.0.12
        if: steps.ref_name.outputs.tag != ''
        with:
          context: ${{ github.workspace }}/images/app
          image: shopstic/k8s-resource-replicator
          tag: ${{ steps.ref_name.outputs.tag }}
          skipIfExists: false

      - name: Build and push Helm Chart
        if: steps.ref_name.outputs.tag != ''
        env:
          SHELL_IMAGE: ${{ needs.build-env.outputs.image }}
          GITHUB_TAG: ${{ steps.ref_name.outputs.tag }}
        run: |-
          cat <<EOF | docker run \
            --workdir /repo \
            -i \
            --rm \
            -e GITHUB_SHA \
            -v "${GITHUB_WORKSPACE}:/repo" \
            -v "${HOME}/.docker/config.json:/root/.docker/config.json" \
            "${SHELL_IMAGE}" \
            bash -l
          set -euo pipefail

          export HELM_EXPERIMENTAL_OCI=1
          export HELM_REGISTRY_CONFIG=/root/.docker/config.json

          yq e '.appVersion = env(GITHUB_SHA)' -i ./charts/resource-replicator/Chart.yaml 
          helm chart save ./charts/resource-replicator "ghcr.io/shopstic/chart-resource-replicator:${GITHUB_SHA}"
          helm chart push "ghcr.io/shopstic/chart-resource-replicator:${GITHUB_SHA}"
          
          EOF