name: Dev

on:
  push:
    branches-ignore:
      - "releases/*"
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build-x86_64:
    name: Build x86_64
    runs-on: ubuntu-20.04
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: ./.github/actions/build
        id: build
        with:
          tailscaleAuthKey: ${{ secrets.TAILSCALE_AUTHKEY }}
          nixBuildSshKey: ${{ secrets.NIX_BUILD_SSH_KEY }}
          dockerHubUsername: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
          arch: x86_64
      - run: sudo tailscale logout

  build-aarch64:
    name: Build aarch64
    runs-on: ubuntu-20.04
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: ./.github/actions/build
        id: build
        with:
          tailscaleAuthKey: ${{ secrets.TAILSCALE_AUTHKEY }}
          nixBuildSshKey: ${{ secrets.NIX_BUILD_SSH_KEY }}
          dockerHubUsername: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
          arch: aarch64
      - run: sudo tailscale logout

  push:
    name: Push
    runs-on: ubuntu-20.04
    needs: [build-x86_64, build-aarch64]
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - run: chmod +r ~/.docker/config.json

      - name: Push multi-arch manifests
        shell: nix develop -v -c bash {0}
        env:
          AMD64_DIGEST: ${{ needs.build-x86_64.outputs.digest }}
          ARM64_DIGEST: ${{ needs.build-aarch64.outputs.digest }}
          IMAGE_TAG: dev-${{ github.sha }}
        run: |-
          ./release.sh push_multi_arch_manifest "${IMAGE_TAG}" "${AMD64_DIGEST:?"Missing AMD64_DIGEST"}" "${ARM64_DIGEST:?"Missing ARM64_DIGEST"}"

      - name: Push Helm chart
        shell: nix develop -v -c bash {0}
        env:
          HELM_CHART_VERSION: 1.0.0-${{ github.sha }}
          HELM_APP_VERSION: dev-${{ github.sha }}
          HELM_CHART_REF: oci://ghcr.io/shopstic/k8s-resource-replicator/chart
        run: |-
          ./release.sh push_helm_chart "${HELM_CHART_VERSION}" "${HELM_APP_VERSION}" "${HELM_CHART_REF}"
