name: Dev

on:
  push:
    branches-ignore:
      - "releases/*"
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build-x86_64:
    name: Build x86_64
    runs-on: [self-hosted, nix]
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: ./.github/actions/build
        id: build
        with:
          imageRepo: public.ecr.aws/g1b1f7a7/k8s-resource-replicator
          arch: x86_64

  build-aarch64:
    name: Build aarch64
    runs-on: [self-hosted, nix]
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: ./.github/actions/build
        id: build
        with:
          imageRepo: public.ecr.aws/g1b1f7a7/k8s-resource-replicator
          arch: aarch64

  push:
    name: Push
    runs-on: [self-hosted, nix]
    needs: [build-x86_64, build-aarch64]
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push multi-arch manifests
        shell: nix develop -v -c bash {0}
        env:
          AMD64_DIGEST: ${{ needs.build-x86_64.outputs.digest }}
          ARM64_DIGEST: ${{ needs.build-aarch64.outputs.digest }}
          IMAGE_TAG: dev-${{ github.sha }}
        run: |-
          ./release.sh push_multi_arch_manifest \
            public.ecr.aws/g1b1f7a7/k8s-resource-replicator \
            "${IMAGE_TAG}" \
            "${AMD64_DIGEST:?"Missing AMD64_DIGEST"}" \
            "${ARM64_DIGEST:?"Missing ARM64_DIGEST"}"

      - name: Push Helm chart
        shell: nix develop -v -c bash {0}
        env:
          HELM_CHART_VERSION: 1.0.0-${{ github.sha }}
          HELM_APP_VERSION: dev-${{ github.sha }}
        run: |-
          ./release.sh push_helm_chart \
            "${HELM_CHART_VERSION}" \
            "${HELM_APP_VERSION}" \
            oci://public.ecr.aws/g1b1f7a7/k8s-resource-replicator-chart