name: Dev

on:
  push:
    branches-ignore:
      - "releases/*"
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Build x86_64
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - run: |-
          whoami
          ls -la
          which nix
          nix --version