name: Build Shell

on:
  push:
    branches: [main]
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Buildkit
        uses: moby/buildkit:master-rootless
        env:
          DOCKER_IMAGE_HASH: ${{ hashFiles('shell/*') }}
          BUILD_CACHE: /home/runner/.docker/buildkit
        with:
          entrypoint: buildctl-daemonless.sh
          args: build --frontend dockerfile.v0 --local context=/github/workspace/shell --local dockerfile=/github/workspace/shell
